-- Create WORK_ITEM_DETAILS_LATEST_VIEW
-- This view provides only the latest version of each work item from WORK_ITEM_DETAILS_BQ
-- This eliminates duplicates and ensures other views that reference it get clean data

CREATE OR REPLACE VIEW `red-octane-444308-f4.karbon_data.WORK_ITEM_DETAILS_LATEST_VIEW` AS

SELECT 
  -- All fields from WORK_ITEM_DETAILS_BQ
  WORK_ITEM_ID,
  REPORTING_DATE,
  WORK_TITLE,
  CLIENT_ID,
  CLIENT,
  CLIENT_TYPE,
  INTERNAL_CLIENT_ID,
  INTERNAL_CLIENT,
  ACCOUNT_ID,
  ACCOUNT_NAME,
  WORK_TYPE_ID,
  WORK_TYPE,
  PRIMARY_STATUS_ID,
  SECONDARY_STATUS_ID,
  PRIMARY_STATUS,
  SECONDARY_STATUS,
  SECONDARY_STATUS_ORDER,
  CURRENT_STATUS_ENTRY_DATE,
  REPEAT_SCHEDULE,
  CREATED_DATETIME,
  CREATED_BY_ID,
  CREATED_BY,
  START_DATETIME,
  ASSIGNED_TO_ID,
  ASSIGNED_TO,
  DUE_DATETIME,
  DEADLINE_DATETIME,
  COMPLETED_DATETIME,
  COMPLETED_BY_ID,
  COMPLETED_BY,
  USER_DEFINED_CLIENT_ID,
  WORK_TEMPLATE_ID,
  WORK_TEMPLATE,
  WORK_DESCRIPTION,
  FIXED_FEE_ESTIMATED_COST,
  BUDGETED_MINUTES,
  BUDGETED_COST,
  EXPENSE_AMOUNT,
  BILLABLE_EXPENSE_AMOUNT,
  TIME_ENTRY_MINUTES,
  TIME_ENTRY_COST,
  BUDGET_REMAINING_HOURS,
  INTERNAL_TASKS_COMPLETED_COUNT,
  INTERNAL_TASKS_PENDING_COUNT,
  IS_WORK_ITEM_OVERDUE

FROM `red-octane-444308-f4.karbon_data.WORK_ITEM_DETAILS_BQ` main

-- Filter to only show the latest version of each work item
WHERE main.REPORTING_DATE = (
  SELECT MAX(REPORTING_DATE) 
  FROM `red-octane-444308-f4.karbon_data.WORK_ITEM_DETAILS_BQ` latest
  WHERE latest.WORK_ITEM_ID = main.WORK_ITEM_ID
)

-- Order by work item for consistent results
ORDER BY WORK_ITEM_ID; 